#!/bin/bash
# edgy-skills — Cursor Adapter
# Generoi .cursorrules tiedoston valituista skillseistä
#
# Käyttö:
#   bash install.sh edgy-framework
#   bash install.sh edgy-framework edgy-assessment
#   bash install.sh --source=gh edgy-framework      # pakota gh-lähde (private repo)

set -euo pipefail

# Lataa jaettu lähdestrategia
ADAPTER_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${ADAPTER_SCRIPT_DIR}/../_shared/source.sh"

CURSORRULES_FILE="${PWD}/.cursorrules"

log_info()  { echo -e "${GREEN}✓${NC} $1"; }
log_warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1" >&2; }

# Parsi --source=... ja skill-id:t
ARGS=()
for arg in "$@"; do
  case "$arg" in
    --source=*) SOURCE_MODE="${arg#--source=}" ;;
    --help|-h)
      echo "Käyttö: $0 [--source=local|gh|curl] <skill-id> [skill-id2 ...]"
      exit 0
      ;;
    *) ARGS+=("$arg") ;;
  esac
done

if [[ ${#ARGS[@]} -eq 0 ]]; then
  echo "Käyttö: $0 [--source=local|gh|curl] <skill-id> [skill-id2 ...]"
  exit 1
fi

if ! command -v python3 &>/dev/null; then
  log_error "python3 ei löydy."
  exit 1
fi

source_detect
log_info "Lähde: ${SOURCE_MODE}"

registry_file=$(source_fetch_registry) || exit 1

# Aloita .cursorrules
{
  echo "# .cursorrules — Generated by edgy-skills"
  echo "# Source: ${SOURCE_MODE} (${REGISTRY_REPO}@${REGISTRY_BRANCH})"
  echo "# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "#"
  echo "# Skills included:"
  for skill in "${ARGS[@]}"; do echo "#   - $skill"; done
  echo ""
} > "$CURSORRULES_FILE"

for skill_id in "${ARGS[@]}"; do
  # Validoi skill-id
  if [[ ! "$skill_id" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    log_error "Virheellinen skill-id: '${skill_id}'"
    continue
  fi

  if ! skill_path=$(python3 "$LOOKUP_TOOL" path "$skill_id" "$registry_file"); then
    log_error "Skilliä '${skill_id}' ei löydy registry.yaml:sta"
    continue
  fi

  echo "---" >> "$CURSORRULES_FILE"
  echo "# SKILL: ${skill_id}" >> "$CURSORRULES_FILE"
  echo "" >> "$CURSORRULES_FILE"

  if ! source_fetch_file "${skill_path}/SKILL.md" >> "$CURSORRULES_FILE"; then
    log_error "SKILL.md:n haku epäonnistui: ${skill_path}/SKILL.md"
    continue
  fi
  echo "" >> "$CURSORRULES_FILE"
  log_info "Skill '${skill_id}' lisätty .cursorrules:iin"
done

log_info "Valmis! ${CURSORRULES_FILE} on päivitetty."
